
inherit_from: .rubocop_todo.yml


LineLength:
  Max: 160

Documentation:
  Enabled: false

ParameterLists:
  Max: 15

MethodLength:
  Max: 50

RegexpLiteral:
  Enabled: false

AllCops:
  Excludes:
    - spec/dummy_app/**
