language: ruby
rvm:
  - 2.1.5
  - 2.2.1
  - 2.3.1
  - 2.4.0
  - 2.7.0
script: bundle exec rake spec rubocop
cache: bundler
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
